# Generated by Django 2.2.12 on 2020-05-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0003_buku'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='no_isbn',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
