# Generated by Django 2.2.12 on 2020-05-11 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0004_buku_no_isbn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buku',
        ),
    ]
