# Generated by Django 2.2.12 on 2020-05-11 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0009_buku_jumlah'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buku',
        ),
    ]
