# Generated by Django 2.2.12 on 2020-06-28 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0016_auto_20200628_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buku',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='buku',
            name='tanggal',
        ),
    ]
